# Generated by Django 5.1.6 on 2025-02-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='remarks',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
